name: TERRAFORM MODULE MATRIX

on:
  workflow_call:
    inputs:
      github_runner:
        description: 'Name of GitHub-hosted runner or self-hosted runner'
        default: 'ubuntu-latest'
        required: false
        type: string
      tofu_version:
        description: 'OpenTofu version used inside GitHub Actions'
        default: 'latest'
        required: false
        type: string
      tofu_working_directory:
        description: 'A relative path starting with "." that OpenTofu will execute within (e.g. "./infrastructure")'
        default: '.'
        required: false
        type: string
      enable_terraform_docs:
        description: 'Enable automatic generation of documentation with terraform-docs'
        default: true
        required: false
        type: boolean
      tflint_repo_name:
        description: 'Public repo where tflint config is stored'
        default: 'nuvibit/github-tflint-config'
        required: false
        type: string
      tflint_repo_config_path:
        description: 'Path to tflint config in tflint_repo (e.g. "aws/.tflint.hcl")'
        default: 'aws/.tflint.hcl'
        required: false
        type: string
      tflint_repo_ref:
        description: 'Ref or branch of tflint_repo'
        default: 'main'
        required: false
        type: string
      tflint_version:
        description: 'Tflint version to use in GitHub Actions'
        default: 'latest'
        required: false
        type: string
      trivy_version:
        description: 'Trivy version to use in GitHub Actions'
        default: 'latest'
        required: false
        type: string
      examples_path:
        description: 'Path to examples directory'
        default: 'examples'
        required: false
        type: string
      commit_user:
        description: 'Username which should be used for commits by github action'
        default: 'github-actions'
        required: false
        type: string
      commit_email:
        description: 'Email which should be used for commits by github action'
        default: 'noreply@github.com'
        required: false
        type: string
      terraform_modules_github_owner:
        description: 'GitHub owner for private Terraform modules'
        default: ''
        required: false
        type: string
      terraform_modules_auth:
        description: 'Authentication method for private Terraform modules (e.g., github-app)'
        default: 'github-app'
        required: false
        type: string
      aws_default_region:
        description: 'Default AWS region for AWS credentials'
        default: 'eu-central-1'
        required: false
        type: string
      aws_oidc_role_arn:
        description: 'AWS OIDC Role ARN for assuming AWS credentials'
        default: ''
        required: false
        type: string
    secrets:
      GH_APP_PRIVATE_KEY:
        required: true   
      GH_APP_ID:
        required: true
      NTC_GITHUB_ACCESS_TOKEN:
        required: true
      TERRAFORM_MODULES_APP_ID:
        required: false
      TERRAFORM_MODULES_APP_PRIVATE_KEY:
        required: false

jobs:

  fmt:
    runs-on: ${{ inputs.github_runner }}
    outputs:
      fmt_status: ${{ steps.fmt.outcome }}
      diff_exists: ${{ steps.fmt_commit.outputs.diff }}

    steps:
      - name: Generate token for GH App in foen-admin-ch organization
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # create a token for the current repository

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.tofu_version }}

      - name: OpenTofu Format
        id: fmt
        run: tofu fmt -recursive
        working-directory: ${{ inputs.tofu_working_directory }}

      - name: Commit files
        id: fmt_commit
        run: |
          git config --global url."https://oauth2:${{ steps.generate-token.outputs.token }}@github.com".insteadOf https://github.com
          git config --local user.name "${{ inputs.commit_user }}"
          git config --local user.email "${{ inputs.commit_email }}"
          if [[ -z $(git status -s) ]]; then
            echo "diff=false" >> $GITHUB_OUTPUT
          else
            echo "diff=true" >> $GITHUB_OUTPUT
          fi
          git diff-index --quiet HEAD || git commit -m "style(tofu fmt): format code" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref || github.ref }}

  docs:
    needs:
      - fmt
    if: ${{ needs.fmt.outputs.diff_exists == 'false' }}
    runs-on: ${{ inputs.github_runner }}
    outputs:
      docs_status: ${{ steps.docs.outcome }}
      diff_exists: ${{ steps.docs.outputs.num_changed > 0 }}

    steps:
      - name: Generate token for GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # create a token for the current repository

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set Git Access Token
        run: |
          git config --global url."https://oauth2:${{ steps.generate-token.outputs.token }}@github.com".insteadOf https://github.com

      - name: Docs
        id: docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ${{ inputs.tofu_working_directory }}
          output-file: README.md
          output-method: inject
          args: --sort-by required
          git-push: true
          git-push-user-name: ${{ inputs.commit_user }}
          git-push-user-email: ${{ inputs.commit_email }}
          git-commit-message: "docs(docs): update readme"

  lint:
    needs:
      - fmt
      - docs
    if: ${{ needs.fmt.outputs.diff_exists == 'false' && needs.docs.outputs.diff_exists == 'false' }}
    runs-on: ${{ inputs.github_runner }}
    outputs:
      lint_status: ${{ steps.lint.outcome }}

    steps:
      - name: Generate token for GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # create a token for the current repository

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Get TFLint Config
        uses: terraform-linters/tflint-load-config-action@v2
        if: ${{ inputs.tflint_repo_config_path != '' }}
        with:
          source-repo: ${{ inputs.tflint_repo_name }}
          source-path: ${{ inputs.tflint_repo_config_path }}
          source-ref: ${{ inputs.tflint_repo_ref }}
          destination-path: .tflint.hcl
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run TFLint
        uses: reviewdog/action-tflint@v1
        id: lint
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          working_directory: ${{ inputs.tofu_working_directory }}
          tflint_version: ${{ inputs.tflint_version }}
          reporter: github-pr-check
          fail_level: error
          filter_mode: nofilter
          level: error
          flags: ""
          tflint_init: true

  security:
    needs:
      - fmt
      - docs
      - lint
    if: ${{ needs.fmt.outputs.diff_exists == 'false' && needs.docs.outputs.diff_exists == 'false' }}
    runs-on: ${{ inputs.github_runner }}
    outputs:
      security_status: ${{ steps.security-gate.outcome }}

    steps:
      - name: Generate token for GitHub App in foen-admin-ch organization
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # create a token for the current repository

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ steps.generate-token.outputs.token }}
      
      - name: Run Trivy Scan
        uses: reviewdog/action-trivy@v1
        id: security-scan
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          working_directory: ${{ inputs.examples_path }}
          reporter: github-pr-check
          fail_level: none
          filter_mode: nofilter
          level: error
          flags: ""
          trivy_flags: ""
          trivy_command: config
          trivy_target: .
          trivy_version: ${{ inputs.trivy_version }}

      - name: Run Trivy Quality Gate
        uses: reviewdog/action-trivy@v1
        id: security-gate
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          working_directory: ${{ inputs.examples_path }}
          reporter: github-pr-check
          fail_level: error
          filter_mode: nofilter
          level: error
          flags: ""
          trivy_flags: "--severity CRITICAL,HIGH"
          trivy_command: config
          trivy_target: .
          trivy_version: ${{ inputs.trivy_version }}

  tofu-test:
    needs:
      - fmt
      - docs
      - lint
      - security
    # this job should only run if there are no new commits caused by terraform-fmt or terraform-docs
    # if terraform-docs is disabled, it should only run if terraform-fmt caused no changes
    # also only run this job if terraform execution is enabled
    if: ${{ always() && !failure() && !cancelled() && needs.fmt.outputs.diff_exists == 'false' && (!inputs.enable_terraform_docs || needs.docs.outputs.diff_exists == 'false') }}
    runs-on: ${{ inputs.github_runner }}
    outputs:
      test_status: ${{ steps.test.outcome }}

    steps:
      - name: Generate token for GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # create a token for the current repository

      - name: Get Private Module Access Token
        if: ${{ inputs.terraform_modules_auth == 'github-app' }}
        id: private_module_access
        uses: actions/create-github-app-token@v2
        env:
          TERRAFORM_MODULES_APP_ID: ${{ secrets.TERRAFORM_MODULES_APP_ID }}
          TERRAFORM_MODULES_APP_PRIVATE_KEY: ${{ secrets.TERRAFORM_MODULES_APP_PRIVATE_KEY }}
        with:
          app-id: ${{ secrets.TERRAFORM_MODULES_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_MODULES_APP_PRIVATE_KEY }}
          # If owner is set and repositories is empty, access will be scoped to all repositories in the provided repository owner's installation
          owner: ${{ inputs.terraform_modules_github_owner }}
        continue-on-error: true

      - name: Set Private Module Access Token
        if: ${{ inputs.terraform_modules_auth == 'github-app' && steps.private_module_access.outputs.token != '' }}
        run: |
          git config --global url."https://x-access-token:${{ steps.private_module_access.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Set Private NTC Module Access Token
        env:
          NTC_GITHUB_ACCESS_TOKEN: ${{ secrets.NTC_GITHUB_ACCESS_TOKEN }}
        if: ${{ env.NTC_GITHUB_ACCESS_TOKEN != '' }}
        run: |
         git config --global url."https://${{ secrets.NTC_GITHUB_ACCESS_TOKEN }}@github.com/nuvibit-terraform-collection".insteadOf "https://github.com/nuvibit-terraform-collection"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ensure that the checkout action does not persist credentials to not override private module access
          persist-credentials: false

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.tofu_version }}
          tofu_wrapper: false

      - name: Configure AWS credentials
        if: ${{ inputs.aws_oidc_role_arn != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_oidc_role_arn }}
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ inputs.aws_default_region }}
          role-duration-seconds: 3600

      - name: tofu init
        id: init
        run: |
          tofu init
        working-directory: ${{ inputs.tofu_working_directory }}

      - name: tofu test
        id: test
        run: |
          tofu test
        working-directory: ${{ inputs.tofu_working_directory }}

      - name: Terraform Test Summary
        run: |
          echo '### TERRAFORM TEST SUMMARY :rocket:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '**Status:** `${{ steps.test.outcome }}`' >> $GITHUB_STEP_SUMMARY
          echo '**Triggered by:** @${{ github.actor }}' >> $GITHUB_STEP_SUMMARY
          echo '**Action:** `${{ github.event_name }}`' >> $GITHUB_STEP_SUMMARY
          echo '**Branch:** `${{ github.ref }}`' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '<details><summary>Show Apply Output</summary>' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.test.outputs.stdout }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY
          

  workflow-summary:
    needs:
      - fmt
      - docs
      - lint
      - security
      - tofu-test
    runs-on: ${{ inputs.github_runner }}
    if: ${{ always() }}

    steps:
      - name: Workflow Summary
        env:
          TF_FMT_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.fmt.outputs.fmt_status != 'success'] }}
          TF_DOCS_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.docs.outputs.docs_status != 'success'] }}
          TF_LINT_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.lint.outputs.lint_status != 'success'] }}
          TF_SECURITY_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.security.outputs.security_status != 'success'] }}
          TF_TEST_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.tofu-test.outputs.test_status != 'success'] }}
        run: |
          echo '### WORKFLOW SUMMARY :octocat:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '| result | job |' >> $GITHUB_STEP_SUMMARY
          echo '|---|---|' >> $GITHUB_STEP_SUMMARY
          echo '| ${{ env.TF_FMT_RESULT }} | tofu format |' >> $GITHUB_STEP_SUMMARY
          echo '| ${{ env.TF_DOCS_RESULT }} | terraform docs |' >> $GITHUB_STEP_SUMMARY
          echo '| ${{ env.TF_LINT_RESULT }} | terraform lint |' >> $GITHUB_STEP_SUMMARY
          echo '| ${{ env.TF_SECURITY_RESULT }} | trivy security |' >> $GITHUB_STEP_SUMMARY
          echo '| ${{ env.TF_TEST_RESULT }} | tofu test |' >> $GITHUB_STEP_SUMMARY
